-- EMPLOYEE TABLE: INITIAL LOAD EXAMPLE DATA
INSERT INTO EMPLOYEE (ID, NAME, SURNAME) VALUES (1001, 'AEmployeeSampleName001','AEmployeeSampleSurname001');
INSERT INTO EMPLOYEE (ID, NAME, SURNAME) VALUES (1002, 'AEmployeeSampleName002','AEmployeeSampleSurname002');
INSERT INTO EMPLOYEE (ID, NAME, SURNAME) VALUES (1003, 'AEmployeeSampleName003','AEmployeeSampleSurname003');